//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSAVault.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSAVault.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de ....
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor permita el acceso.
        /// </summary>
        internal static string AllowAccess {
            get {
                return ResourceManager.GetString("AllowAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cómprame un café.
        /// </summary>
        internal static string BuyMeACoffe {
            get {
                return ResourceManager.GetString("BuyMeACoffe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificado.
        /// </summary>
        internal static string Certificate {
            get {
                return ResourceManager.GetString("Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificados.
        /// </summary>
        internal static string Certificates {
            get {
                return ResourceManager.GetString("Certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificados &amp; llaves.
        /// </summary>
        internal static string CertificatesKeys {
            get {
                return ResourceManager.GetString("CertificatesKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar a ingles.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar.
        /// </summary>
        internal static string Clean {
            get {
                return ResourceManager.GetString("Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Limpiar texto?.
        /// </summary>
        internal static string CleanTextAsk {
            get {
                return ResourceManager.GetString("CleanTextAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear certificado.
        /// </summary>
        internal static string CreateCertificate {
            get {
                return ResourceManager.GetString("CreateCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desarrollada por: Jonathan Eduardo G.G.
        /// </summary>
        internal static string DevelopedBy {
            get {
                return ResourceManager.GetString("DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta App fue desarrollada con la fines didacticos al ilustrar de forma sencilla la entropía de Shannon..
        /// </summary>
        internal static string DevelopedFor {
            get {
                return ResourceManager.GetString("DevelopedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encriptado: .
        /// </summary>
        internal static string Encrypted {
            get {
                return ResourceManager.GetString("Encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eventos equiprobables.
        /// </summary>
        internal static string EquiProbable {
            get {
                return ResourceManager.GetString("EquiProbable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrio un error abriendo este archivo, prueba con uno diferente....
        /// </summary>
        internal static string ErrorPickingFile {
            get {
                return ResourceManager.GetString("ErrorPickingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vencimiento.
        /// </summary>
        internal static string Expire {
            get {
                return ResourceManager.GetString("Expire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitar bloqueo por huella.
        /// </summary>
        internal static string FingerPrint {
            get {
                return ResourceManager.GetString("FingerPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encriptar texto.
        /// </summary>
        internal static string FromText {
            get {
                return ResourceManager.GetString("FromText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protega texto al instante.
        /// </summary>
        internal static string FromTextSubtitle {
            get {
                return ResourceManager.GetString("FromTextSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dale un vistazo al proyecto en Github.
        /// </summary>
        internal static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite el acceso a la galeria para que puedas seleccionar fotos de tu dispositivo y ocultar texto en ellas..
        /// </summary>
        internal static string GrantCamera {
            get {
                return ResourceManager.GetString("GrantCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite el acceso a la camara para que puedas tomar fotos de tu alrededor y ocultar texto en ellas..
        /// </summary>
        internal static string GrantPhotos {
            get {
                return ResourceManager.GetString("GrantPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha denegado el acceso a su camera, por favor permita el acceso desde ajustes de su dispositivo.
        /// </summary>
        internal static string HasDeniedCamera {
            get {
                return ResourceManager.GetString("HasDeniedCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha denegado el acceso a la galeria,por favor permita el acceso desde ajustes de su dispositivo.
        /// </summary>
        internal static string HasDeniedPhotos {
            get {
                return ResourceManager.GetString("HasDeniedPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha denegado el acceso a su almacenamiento por favor permita el acceso desde ajustes de su dispositivo.
        /// </summary>
        internal static string HasDeniedStorage {
            get {
                return ResourceManager.GetString("HasDeniedStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocultar.
        /// </summary>
        internal static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oculte texto en una imagen.
        /// </summary>
        internal static string HidePicture {
            get {
                return ResourceManager.GetString("HidePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oculte texto en una imagen utilizando esteganografía.
        /// </summary>
        internal static string HidePictureSubtitle {
            get {
                return ResourceManager.GetString("HidePictureSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen :.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo seleccionado no es una imagen.
        /// </summary>
        internal static string ItsAFileNotAnImage {
            get {
                return ResourceManager.GetString("ItsAFileNotAnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licencias y créditos.
        /// </summary>
        internal static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bóveda - RSA.
        /// </summary>
        internal static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meses.
        /// </summary>
        internal static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre: .
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo certificado.
        /// </summary>
        internal static string NewCertificate {
            get {
                return ResourceManager.GetString("NewCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notas privadas.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenga sus notas privadas seguras.
        /// </summary>
        internal static string NotesSubtitle {
            get {
                return ResourceManager.GetString("NotesSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo seleccionado no es un archivo de texto plano, si continua la lectura puede resultar en resultados inesperados.
        ///¿Continuar?.
        /// </summary>
        internal static string NotPlainTextFile {
            get {
                return ResourceManager.GetString("NotPlainTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña: .
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor espere....
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nunca veremos ni compartiremos tus fotos por ningun medio..
        /// </summary>
        internal static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportar un bug.
        /// </summary>
        internal static string ReportBug {
            get {
                return ResourceManager.GetString("ReportBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitar una nueva característica.
        /// </summary>
        internal static string RequestFeature {
            get {
                return ResourceManager.GetString("RequestFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar como nota.
        /// </summary>
        internal static string SaveAsNote {
            get {
                return ResourceManager.GetString("SaveAsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartir.
        /// </summary>
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agradecimiento especial a &quot;Tapia Sanchez Daniel&quot; por su excelente labor docente..
        /// </summary>
        internal static string SpecialThanks {
            get {
                return ResourceManager.GetString("SpecialThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomar fotografía.
        /// </summary>
        internal static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto: .
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un momento....
        /// </summary>
        internal static string WaitASecond {
            get {
                return ResourceManager.GetString("WaitASecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo sentimos....
        /// </summary>
        internal static string WeAreSorry {
            get {
                return ResourceManager.GetString("WeAreSorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creado con la tecnología multiplataforma Xamarin.Forms.
        /// </summary>
        internal static string Xamarin {
            get {
                return ResourceManager.GetString("Xamarin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Puede modificar el acceso en cualquier momento desde la aplicación de ajustes..
        /// </summary>
        internal static string YouCanDisableThis {
            get {
                return ResourceManager.GetString("YouCanDisableThis", resourceCulture);
            }
        }
    }
}
